name: inventpilot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  mobile_scanner: ^3.5.0
  uuid: ^4.0.0 
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/user_placeholder.png
